title: ChrHan's Microblog
author: ChrHan
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Yet another DevOps microblog - hosted at GitHub Pages! 

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  ChrHan # DO NOT include the @ character, or else the build will fail!

google_analytics: UA-40305679-1

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
