title: ChrHan's Microblog
author: ChrHan
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Yet another DevOps microblog - hosted at GitHub Pages! 

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username: ChrHan # DO NOT include the @ character, or else the build will fail!

google_analytics: UA-40305679-1
google_analytics_ga4: G-7K77YKH00F

show_excerpts: true # set to false to remove excerpts on the homepage
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-feed

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
 
